name: deploy dev

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    # this prevents concurrent builds
    concurrency: dev-environment

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # this is required for authenticating to AWS via the OIDC Provider we set up
    permissions:
      id-token: write
      contents: write

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::462920085534:role/GitHubActionsRole
          role-session-name: GithubActionsSession

      - name: npm ci
        run: npm ci

      - name: generate fresh .env file
        run: npm run dotEnv

      - name: deploy to dev
        run: npx sls deploy

      - name: run integration test
        run: npm run test

      - name: run end-to-end tests
        run: npm run test:e2e
